# fly.toml app configuration file generated for oliverlabs on 2023-07-23T14:09:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oliverlabs"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
