# fly.toml app configuration file generated for oliverlabs on 2023-07-23T14:41:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oliverlabs"
primary_region = "lhr"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
